import type { CursorToken } from '../types.js';

/**
 * Encode a cursor token as a base64url string.
 *
 * Cursor tokens are opaque pagination markers that encode the last-seen
 * sort key tuple alongside schema_version and command for validation.
 */
export function encodeCursor(token: CursorToken): string {
  const json = JSON.stringify(token);
  // base64url: standard base64 with + → -, / → _, no padding
  return Buffer.from(json, 'utf-8')
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

/**
 * Decode a base64url cursor string into a CursorToken.
 *
 * Throws with code INVALID_CURSOR if:
 * - The string is not valid base64url
 * - The decoded JSON is malformed
 * - schema_version does not match 'v1'
 * - command does not match expectedCommand
 */
export function decodeCursor(encoded: string, expectedCommand: string): CursorToken {
  let json: string;
  try {
    // Restore standard base64 from base64url
    const base64 = encoded.replace(/-/g, '+').replace(/_/g, '/');
    json = Buffer.from(base64, 'base64').toString('utf-8');
  } catch {
    throw cursorError('Cursor token is not valid base64url.');
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(json);
  } catch {
    throw cursorError('Cursor token contains invalid JSON.');
  }

  if (
    typeof parsed !== 'object' ||
    parsed === null ||
    Array.isArray(parsed)
  ) {
    throw cursorError('Cursor token is not a valid object.');
  }

  const obj = parsed as Record<string, unknown>;

  if (obj.schema_version !== 'v1') {
    throw cursorError(
      `Cursor schema_version "${String(obj.schema_version)}" does not match "v1". ` +
        'This cursor may be from a different version of the tool.',
    );
  }

  if (obj.command !== expectedCommand) {
    throw cursorError(
      `Cursor command "${String(obj.command)}" does not match expected "${expectedCommand}". ` +
        'This cursor was generated by a different command.',
    );
  }

  if (
    typeof obj.keys !== 'object' ||
    obj.keys === null ||
    Array.isArray(obj.keys)
  ) {
    throw cursorError('Cursor token has invalid or missing keys.');
  }

  return {
    schema_version: 'v1',
    command: expectedCommand,
    keys: obj.keys as Record<string, string | number>,
  };
}

/**
 * Create an error with a code property for structured error handling.
 */
function cursorError(message: string): Error & { code: string } {
  const err = new Error(message) as Error & { code: string };
  err.code = 'INVALID_CURSOR';
  return err;
}
